/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Manufacturer from './Manufacturer';





/**
* The InventoryItem model module.
* @module model/InventoryItem
* @version 1.0.0
*/
export default class InventoryItem {
    /**
    * Constructs a new <code>InventoryItem</code>.
    * @alias module:model/InventoryItem
    * @class
    * @param id {String} 
    * @param name {String} 
    * @param releaseDate {String} 
    * @param manufacturer {module:model/Manufacturer} 
    */

    constructor(id, name, releaseDate, manufacturer) {
        

        
        

        this['id'] = id;this['name'] = name;this['releaseDate'] = releaseDate;this['manufacturer'] = manufacturer;

        
    }

    /**
    * Constructs a <code>InventoryItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InventoryItem} obj Optional instance to populate.
    * @return {module:model/InventoryItem} The populated <code>InventoryItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryItem();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('releaseDate')) {
                obj['releaseDate'] = ApiClient.convertToType(data['releaseDate'], 'String');
            }
            if (data.hasOwnProperty('manufacturer')) {
                obj['manufacturer'] = Manufacturer.constructFromObject(data['manufacturer']);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} releaseDate
    */
    releaseDate = undefined;
    /**
    * @member {module:model/Manufacturer} manufacturer
    */
    manufacturer = undefined;








}


